### ISSUE TITLE
Dynamic queries and combining existing queries

### ISSUE THREAD

**Issue by sadomovalex** [sadomovalex/camlex#14]
<b>powareverb[CodePlex]</b> <br />First of all, thanks so much for the library. It's been immensely helpful for many projects so far, much better than dealing with CAML strings for sure.

So I'm expecting I'm doing something silly here, but here's the story anyway. Working on CAMLEX 3.3.

I've a pretty typical use case - a simple enough query with a bunch of derivatives. To reduce code, I'm using the dynamic queries syntax to add to the existing query.

So an example base query:
            var simple = CamlexNET.Camlex.Query()
                .Where(
                    p =gt p[quotHelloquot] != null
                );
... and another query to combine:
            var success = CamlexNET.Camlex.Query()
                .WhereAny(
                    simple.ToString(),
                    p =gt p[quotTestquot] != null
                );
                
Console.WriteLine(success.ToString());
Which gives you an output like this:
ltWheregt
  ltOrgt
    ltIsNotNullgt
      ltFieldRef Name=quotTestquot /gt
    lt/IsNotNullgt
    ltIsNotNullgt
      ltFieldRef Name=quotHelloquot /gt
    lt/IsNotNullgt
  lt/Orgt
lt/Wheregt
However, this technique doesn't seem to work for more complex queries, such as the following:
            var expiryDate = quotExpiryDatequot;
            var commenceDate = quotCommencequot;
            var docFolder = quotDocFolderquot;
            var ret = CamlexNET.Camlex.Query()
                .Where(
                        p =gt (p[expiryDate] == null
                            || p[expiryDate] gt (CamlexNET.DataTypes.DateTime)CamlexNET.Camlex.Today) ampamp
                            (p[commenceDate] == null
                            || p[commenceDate] lt= (CamlexNET.DataTypes.DateTime)CamlexNET.Camlex.Today)
                            )
                .GroupBy(p =gt p[docFolder]);
Console.WriteLine(ret.ToString());
You'll see that this generates CAML XML just fine, but when you go to add to it using the same method:
var problem = CamlexNET.Camlex.Query().WhereAny(
                ret.ToString(),
                p =gt p[quotTestquot] != null
            );
Console.WriteLine(problem.ToString());
The last code chunk returns a quotIncorrectCamlExceptionquot, siting that quotCaml specified for tag 'Where' can not be translated to codequot. I'd suggest it's a bug in the CAML to IQuery translation, because throwing the following XML into camlex-online
 also fails (yet this is the CAML that is generated by the quotretquot query above).
ltWheregt
  ltAndgt
    ltOrgt
      ltIsNullgt
        ltFieldRef Name=quotExpiryDatequot /gt
      lt/IsNullgt
      ltGtgt
        ltFieldRef Name=quotExpiryDatequot /gt
        ltValue Type=quotDateTimequotgt
          ltToday /gt
        lt/Valuegt
      lt/Gtgt
    lt/Orgt
    ltOrgt
      ltIsNullgt
        ltFieldRef Name=quotCommencequot /gt
      lt/IsNullgt
      ltLeqgt
        ltFieldRef Name=quotCommencequot /gt
        ltValue Type=quotDateTimequotgt
          ltToday /gt
        lt/Valuegt
      lt/Leqgt
    lt/Orgt
  lt/Andgt
lt/WheregtltGroupBygt
  ltFieldRef Name=quotDocFolderquot /gt
lt/GroupBygt

**Comment by sadomovalex** [comment]
<b>sadomovalex[CodePlex]</b> <br />hi jrath,
yes, Camlex was initially written for Sharepoint 2007, so it doesn't contains all new features, introduced in SP2010 and SP2013. I will add support for TaxonomyFieldTypeMulti to the further development list and will implement it in one of the next releases.

**Comment by sadomovalex** [comment]
<b>jrath[CodePlex]</b> <br />I've debugged the Camlex code and found my error:

It was the TaxonomyFieldTypeMulti. This types are not supported by Camlex and a QueryString with these types can't be processed by Camlex.

**Comment by sadomovalex** [comment]
<b>jrath[CodePlex]</b> <br />I've got the same Problem using Camlex.NET, Version=3.4.0.0, Culture=neutral, PublicKeyToken=831792d54d5285b7:

I want to combine the following queryString with another expression

string queryString (also created with camlex and taxonomy workaround):
Where
  And
    Or
      Eq
        FieldRef Name=ContentType /
        Value Type=Textct1/Value
      /Eq
      Eq
        FieldRef Name=ContentType /
        Value Type=Textct2/Value
      /Eq
    /Or
    Or
      Or
        Or
          Or
            Or
              Or
                Or
                  Eq
                    FieldRef Name=DocumentType /
                    Value Type=TaxonomyFieldTypeMultidocType1/Value
                  /Eq
                  Eq
                    FieldRef Name=DocumentType /
                    Value Type=TaxonomyFieldTypeMultidocType2/Value
                  /Eq
                /Or
                Eq
                  FieldRef Name=DocumentType /
                  Value Type=TaxonomyFieldTypeMultidocType3/Value
                /Eq
              /Or
              Eq
                FieldRef Name=DocumentType /
                Value Type=TaxonomyFieldTypeMultidocType4/Value
              /Eq
            /Or
            Eq
              FieldRef Name=DocumentType /
              Value Type=TaxonomyFieldTypeMultidocType5/Value
            /Eq
          /Or
          Eq
            FieldRef Name=DocumentType /
            Value Type=TaxonomyFieldTypeMultidocType6/Value
          /Eq
        /Or
        Eq
          FieldRef Name=DocumentType /
          Value Type=TaxonomyFieldTypeMulti/Value
        /Eq
      /Or
      IsNull
        FieldRef Name=DocumentType /
      /IsNull
    /Or
  /And
/Where
Code to combine:
Camlex.Query().WhereAll(queryString, i = (string)i[categoryFieldInternalName] == categoryValue);
The result is a CamlexNET.IncorrectCamlException: Caml specified for tag 'Where' can not be translated to code
StackTrace:
   at CamlexNET.Impl.ReverseEngeneering.Caml.ReTranslatorFromCaml.translateWhere(IReAnalyzer analyzer, String tag)
   at CamlexNET.Impl.Query.getWhereExpressionFromString(String existingWhere)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at CamlexNET.Impl.Query.WhereAll(IEnumerable`1 expressions)
   at ........... (my functions)

**Comment by sadomovalex** [comment]
<b>sadomovalex[CodePlex]</b> <br />hello powareverb,
the discussion which you mentioned says that OffsetDays is not supported yet. Today keyword is already supported (and you already use it in your code), so I think that issue is valid. I will check why it is not translated to Caml correctly.

**Comment by sadomovalex** [comment]
<b>powareverb[CodePlex]</b> <br />Actually, sorry, you can close this. After spending more time working on this I realised the issue with the CAML - IQuery was that Today won't be supported, I had to use the discussed workaround here:

[Offset Days][http://camlex.codeplex.com/discussions/270483]

and of course the conversion wouldn't know what to make of it.
