### ISSUE TITLE
Expression type 'MemberAccess' is not supported

### ISSUE THREAD

**Issue by sadomovalex** [sadomovalex/camlex#2]
<b>hodzanassredin[CodePlex]</b> <br />Sample code Query = Camlex.Query()
                                        .Where(x =gt 
                                            (x[SPBuiltInFieldId.ContentTypeId] == (DataTypes.ContentTypeId)WikiContentTypeId ampamp ShowWikiItems)
                                            ampamp (x[SPBuiltInFieldId.ContentTypeId] == (DataTypes.ContentTypeId)BlogContentTypeId ampamp ShowBlogItems)
                                            ampamp (x[SPBuiltInFieldId.ContentTypeId] == (DataTypes.ContentTypeId)ForumContentTypeId ampamp ShowForumItems) 

                                        )

throws exception 
{CamlexNET.NonSupportedExpressionTypeException: Expression type 'MemberAccess' is not supported
at CamlexNET.Impl.Factories.AnalyzerFactory.Create(LambdaExpression expr)
at CamlexNET.Impl.CompositeExpressionBaseAnalyzer.isExpressionValid(Expression subExpr, ParameterExpression lambdaParam)
at CamlexNET.Impl.CompositeExpressionBaseAnalyzer.IsValid(LambdaExpression expr)
at CamlexNET.Impl.Operations.AndAlso.AndAlsoAnalyzer.IsValid(LambdaExpression expr)
at CamlexNET.Impl.CompositeExpressionBaseAnalyzer.isExpressionValid(Expression subExpr, ParameterExpression lambdaParam)
at CamlexNET.Impl.CompositeExpressionBaseAnalyzer.IsValid(LambdaExpression expr)
at CamlexNET.Impl.Operations.AndAlso.AndAlsoAnalyzer.IsValid(LambdaExpression expr)
at CamlexNET.Impl.CompositeExpressionBaseAnalyzer.isExpressionValid(Expression subExpr, ParameterExpression lambdaParam)
at CamlexNET.Impl.CompositeExpressionBaseAnalyzer.IsValid(LambdaExpression expr)
at CamlexNET.Impl.Operations.AndAlso.AndAlsoAnalyzer.IsValid(LambdaExpression expr)
at CamlexNET.Impl.GenericTranslator.TranslateWhere(LambdaExpression expr)
at CamlexNET.Impl.Query.Where(Expression`1 expr)
at ProjectsPrototypeWSP.RecentActivities.GetData(String webUrl)
at ProjectsPrototypeWSP.RecentActivities.OnLoad(EventArgs e)}

**Comment by sadomovalex** [comment]
<b>vtimashkov[CodePlex]</b> <br />Expressions like 
x[fieldName] ==value  someBoolValue 
can't be translated into CAML language. CAML supports only expresions like 
x[fieldName] ==value  x[fieldName2] ==value2  ...

in other words, left part should be indexer and right part should be value (or expression calculated before CAML query is generated).


For the cases, when you need conditional expressions, please use dynamic filter conditions feature implemented in Camlex version 2.


Hope it helps (I am closing the issue).

**Comment by sadomovalex** [comment]
<b>hodzanassredin[CodePlex]</b> <br />booblean value can be translated into something like that 
        0



        0
