### ISSUE TITLE
Expression 'x => new [] {x.get_Item(SPBuiltInFieldId.Modified)}'  can not be translated into CAML

### ISSUE THREAD

**Issue by sadomovalex** [sadomovalex/camlex#3]
<b>hodzanassredin[CodePlex]</b> <br />Query = Camlex.Query()
                                        .Where(x =gt x[SPBuiltInFieldId.ContentTypeId] == (DataTypes.ContentTypeId)quot0x010200133EAACD2B222C4E9F0EEA462F9EA480quot)
                                        .OrderBy(x =gt x[SPBuiltInFieldId.Modified]).ToString(),

throws exception
{CamlexNET.NonSupportedExpressionException: Expression 'x =gt new [] {x.get_Item(SPBuiltInFieldId.Modified)}' can not be translated into CAML
at CamlexNET.Impl.GenericTranslator.TranslateOrderBy(LambdaExpression expr)
at CamlexNET.Impl.Query.OrderBy(Expression1 expr)
at CamlexNET.Impl.Query.OrderBy(Expression1 expr)
at ProjectsPrototypeWSP.RecentActivities.GetData(String webUrl)
at ProjectsPrototypeWSP.RecentActivities.OnLoad(EventArgs e)}

**Comment by sadomovalex** [comment]
<b>sadomovalex[CodePlex]</b> <br />Fixed in 2.0.1.0 version
